export const categories = [
  { value: 'drink', label: 'Drink' },
  { value: 'breakfast', label: 'Breakfast' },
  { value: 'snack', label: 'Snack' },
  { value: 'appetizer', label: 'Appetizer' },
  { value: 'dinner', label: 'Dinner' },
  { value: 'main course', label: 'Main Course' },
  { value: 'side dish', label: 'Side Dish' },
  { value: 'brunch', label: 'Brunch' },
  { value: 'breads', label: 'Breads' },
  { value: 'soup', label: 'Soup' },
  { value: 'holiday cookies', label: 'Holiday Cookies' },
  { value: 'desserts', label: 'Desserts' },
  { value: 'low fat', label: 'Low Fat' },
  { value: 'salad', label: 'Salad' },
  { value: 'dips', label: 'Dips' },
  { value: 'salsas', label: 'Salsas' },
  { value: 'vegetarian', label: 'Vegetarian' },
  { value: 'dairy free', label: 'Dairy Free' },
]

export const Ingredients = [
  { value: 'blackberries', label: 'Blackberries' },
  { value: 'raspberries', label: 'Raspberries' },
  { value: 'blueberries', label: 'Blueberries' },
  { value: 'strawberries', label: 'Strawberries' },
  { value: 'beef', label: 'Beef' },
  { value: 'chicken', label: 'Chicken' },
  { value: 'eggs', label: 'Eggs' },
  { value: 'lentils', label: 'Lentils' },
  { value: 'carrot', label: 'Carrot' },
  { value: 'onion', label: 'Onion' },
  { value: 'garlic', label: 'Garlic' },
  { value: 'parsley', label: 'Parsley' },
  { value: 'celery', label: 'Celery' },
  { value: 'cinnamon', label: 'Cinnamon' },
  { value: 'sugar', label: 'Sugar' },
  { value: 'vanilla', label: 'Vanilla' },
  { value: 'unsweetened applesauce', label: 'Unsweetened Applesauce' },
  { value: 'bread', label: 'Bread' },
  { value: 'cornstarch', label: 'Cornstarch' },
  { value: 'black pepper', label: 'Black Pepper' },
  { value: 'rosemary', label: 'Rosemary' },
  { value: 'thyme', label: 'Thyme' },
]
